manager/urls.py
from django.urls import path

from manager import views

app_name = "manager"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "task-types/",
        views.TaskTypeListView.as_view(),
        name="task-type-list"
    ),
    path(
        "task-types/create/",
        views.TaskTypeCreateView.as_view(),
        name="task-type-create"
    ),
    path(
        "positions/",
        views.PositionListView.as_view(),
        name="position-list"
    ),
    path(
        "positions/create/",
        views.PositionCreateView.as_view(),
        name="position-create"
    ),
    path(
        "workers/",
        views.WorkerListView.as_view(),
        name="worker-list"
    ),
    path(
        "workers/<int:pk>/",
        views.WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path(
        "workers/create/",
        views.WorkerCreateView.as_view(),
        name="worker-create"
    ),
    path(
        "workers/<int:pk>/update/",
        views.WorkerUpdateView.as_view(),
        name="worker-update"
    ),
    path(
        "workers/<int:pk>/delete/",
        views.WorkerDeleteView.as_view(),
        name="worker-delete"
    ),
    path(
        "tasks/",
        views.TaskView.as_view(),
        name="task-list"
    ),
    path(
        "tasks/<int:pk>/",
        views.TaskDetailView.as_view(),
        name="task-detail"
    ),
    path(
        "tasks/create/",
        views.TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "tasks/<int:pk>/update/",
        views.TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        views.TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/completed-task/",
        views.TaskCompletedView.as_view(),
        name="task-completed"
    ),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("manager.urls", namespace="manager")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

manager/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from task_manager.settings import AUTH_USER_MODEL


class TaskType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name


class Position(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(
        Position,
        on_delete=models.CASCADE,
        related_name="workers",
        blank=True,
        null=True
    )

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name} ({self.position})"


class Task(models.Model):
    class Priority(models.TextChoices):
        URGENT = "urgent", "Urgent"
        LOW = "low", "Low"
        MEDIUM = "medium", "Medium"
        HIGH = "high", "High"

    name = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateTimeField()
    is_completed = models.BooleanField()
    task_type = models.ForeignKey(
        TaskType,
        on_delete=models.CASCADE,
        related_name="tasks"
    )
    priority = models.CharField(
        max_length=10,
        choices=Priority.choices,
        default=Priority.HIGH
    )
    assignees = models.ManyToManyField(AUTH_USER_MODEL, related_name="tasks")

    class Meta:
        ordering = ("is_completed", "deadline", )

    def __str__(self) -> str:
        return self.name

manager/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from manager.models import TaskType, Position, Worker, Task


class TaskTypeForm(forms.ModelForm):

    class Meta:
        model = TaskType
        fields = "__all__"


class PositionForm(forms.ModelForm):

    class Meta:
        model = Position
        fields = "__all__"


class WorkerForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "position",
        )


class TaskSearchForm(forms.Form):
    task = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by Task"}
        )
    )


class TaskForm(forms.ModelForm):

    deadline = forms.DateTimeField(
        widget=forms.DateTimeInput(
            attrs={"type": "datetime-local"}
        )
    )
    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Task
        fields = "__all__"

manager/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic

from manager.forms import (
    TaskTypeForm, PositionForm, WorkerForm, TaskSearchForm, TaskForm
)
from manager.models import Task, Worker, TaskType, Position


@login_required
def index(request: HttpRequest) -> HttpResponse:
    actual_tasks = Task.objects.filter(is_completed=False).count()
    completed_tasks = Task.objects.filter(is_completed=True).count()
    workers = Worker.objects.count()

    context = {
        "actual_tasks": actual_tasks,
        "completed_tasks": completed_tasks,
        "workers": workers
    }

    return render(request, "manager/index.html", context=context)


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    template_name = "manager/task_type_list.html"
    paginate_by = 5


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    template_name = "manager/task_type_create.html"
    form_class = TaskTypeForm
    success_url = reverse_lazy("manager:task-type-list")


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    template_name = "manager/position_list.html"
    paginate_by = 5


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    template_name = "manager/position_create.html"
    form_class = PositionForm
    success_url = reverse_lazy("manager:position-list")


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    template_name = "manager/worker_list.html"
    paginate_by = 5


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    template_name = "manager/worker_detail.html"
    context_object_name = "worker"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        worker = self.object

        completed_tasks = Task.objects.filter(
            assignees=worker, is_completed=True
        )
        actual_tasks = Task.objects.filter(
            assignees=worker, is_completed=False
        )

        context["actual_tasks"] = actual_tasks
        context["completed_tasks"] = completed_tasks

        return context


class WorkerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Worker
    form_class = WorkerForm
    template_name = "manager/worker_form.html"
    success_url = reverse_lazy("manager:worker-list")


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerForm
    template_name = "manager/worker_form.html"
    success_url = reverse_lazy("manager:worker-list")


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    template_name = "manager/worker_confirm_delete.html"
    success_url = reverse_lazy("manager:worker-list")


class TaskView(LoginRequiredMixin, generic.ListView):
    model = Task
    template_name = "manager/task_list.html"
    paginate_by = 5

    def get_context_data(self, **kwargs) -> dict:
        context = super(TaskView, self).get_context_data(**kwargs)
        task = self.request.GET.get("task", "")
        context["search_form"] = TaskSearchForm(initial={"task": task})
        return context

    def get_queryset(self):
        queryset = Task.objects.all()
        task = self.request.GET.get("task")
        if task:
            return queryset.filter(name__icontains=task)

        return queryset


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task
    template_name = "manager/task_detail.html"
    context_object_name = "task"


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    template_name = "manager/task_form.html"
    success_url = reverse_lazy("manager:task-list")
    form_class = TaskForm


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    template_name = "manager/task_form.html"
    success_url = reverse_lazy("manager:task-list")
    form_class = TaskForm


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    template_name = "manager/task_confirm_delete.html"
    success_url = reverse_lazy("manager:task-list")


class TaskCompletedView(LoginRequiredMixin, generic.View):
    model = Task

    def post(self, request: HttpRequest, pk: int) -> HttpResponseRedirect:
        task = get_object_or_404(Task, pk=pk)
        task.is_completed = not task.is_completed
        task.save()

        return HttpResponseRedirect(
            reverse("manager:task-detail", kwargs={"pk": pk})
        )

templates/manager/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Home page{% endblock %}

{% block content %}

  {% include "includes/header.html" %}
  
  <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
          <div class="row">
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"><span id="state1" countTo="{{ actual_tasks }}">0</span>+</h1>
                <h5 class="mt-3">Actual tasks</h5>
                <p class="text-sm">Tasks that are waiting to be performed, our specialists are already working on them</p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"> <span id="state2" countTo="{{ completed_tasks }}">0</span>+</h1>
                <h5 class="mt-3">Completed tasks</h5>
                <p class="text-sm">An indicator that we are working</p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary" id="state3" countTo="{{ workers }}">0</h1>
                <h5 class="mt-3">Workers</h5>
                <p class="text-sm">Those who work to make our company better</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  
  <section class="pt-lg-7 pt-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-5 col-md-8 order-2 order-md-2 order-lg-1">
          <div class="position-relative ms-lg-5 mb-0 mb-md-7 mb-lg-0 d-none d-md-block d-lg-block d-xl-block h-75">
            <div class="bg-gradient-dark w-100 h-100 border-radius-xl position-absolute d-lg-block d-none" alt=""></div>
            <img src="{% static 'img/IT/it_01.jpg' %}" class="w-100 border-radius-xl mt-6 ms-lg-5 position-relative z-index-5" alt="">
          </div>
        </div>
        <div class="col-lg-5 col-md-12 ms-auto order-1 order-md-1 order-lg-1">
          <div class="p-3 pt-0">
            <div class="icon icon-shape bg-gradient-dark rounded-circle shadow text-center mb-4">
              <i class="ni ni-building"></i>
            </div>
            <h4 class="mb-4">Task Manager</h4>
            <p>
              Task Manager - this is the development of our company, aimed at facilitating the interaction of employees with each other, quick identification of problems in the project and even faster elimination of problems.
              <br><br>
              In order to find the tasks that have been given to you, follow the link below.
            </p>
            <a href="{% url 'manager:worker-detail' pk=user.pk %}" target="blank" rel="nofollow" class="text-dark icon-move-right">Check Your Tasks
              <i class="fas fa-arrow-right text-sm ms-1"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

{% block javascripts %}
  
  <script src="{% static 'js/plugins/countup.min.js' %}"></script>
  <script src="{% static 'js/plugins/choices.min.js' %}"></script>
  <script src="{% static 'js/plugins/rellax.min.js' %}"></script>
  <script src="{% static 'js/plugins/tilt.min.js' %}"></script>
  <script src="{% static 'js/plugins/choices.min.js' %}"></script>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{% static 'js/soft-design-system.min.js' %}" type="text/javascript"></script>
  <script type="text/javascript">
    if (document.getElementById('state1')) {
      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
      if (!countUp.error) {
        countUp.start();
      } else {
        console.error(countUp.error);
      }
    }
    if (document.getElementById('state2')) {
      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
      if (!countUp1.error) {
        countUp1.start();
      } else {
        console.error(countUp1.error);
      }
    }
    if (document.getElementById('state3')) {
      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
      if (!countUp2.error) {
        countUp2.start();
      } else {
        console.error(countUp2.error);
      };
    }
  </script>
  
{% endblock %}

templates/manager/position_create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Position create{% endblock %}

{% block content %}
      <div class="page-header section-height-100">
    <div class="oblique position-absolute top-0 h-100 d-md-block d-none">
      <div class="oblique-image bg-cover position-absolute fixed-top ms-auto h-100 z-index-0 ms-n6" style="background-image:url(/static/img/IT/it_02.jpg)"></div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-7 d-flex justify-content-center flex-column">
          <h1 class="text-gradient text-danger">Create Position</h1>
          <p class="lead pe-5 me-5">Create your position as needed. </p>
          <form method="post" action="">
            <div class="max-width-500">
              {% csrf_token %}
              {{ form|crispy }}
            </div>
            <div class="buttons">
              <input type="submit" class="btn bg-gradient-primary mt-4" value="Create">
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/manager/position_list.html
{% extends "base.html" %}

{% block title %}Position list{% endblock %}

{% block content %}
  
  {% include "includes/header.html" %}
  
  <div class="container">  
    <div class="position-relative border-radius-xl overflow-hidden shadow-lg mb-7">
      <div class="container border-bottom">
        <div class="row py-3">
          <div class="col-lg-4 text-start">
            <p class="lead text-dark pt-1 mb-0"></p>
          </div>
          <div class="col-lg-4 mt-1 text-center">
            <h1 class="text-dark">Position list</h1>
          </div>
          <div class="col-lg-4 text-end my-auto">
            <a href="{% url 'manager:position-create' %}" class="text-primary icon-move-right">Create new Position
              <i class="fas fa-arrow-right text-sm ms-1" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </div>
      <div>
        {% if position_list %}
          <ul class="list-group-flush">
            {% for position in position_list %}
              <li class="list-group-item">{{ position.name }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>
    </div>
  </div>
  
{% endblock %}

templates/manager/task_confirm_delete.html
{% extends "base.html" %}

{% block title %}Task confirm delete{% endblock %}

{% block content %}
  <div class="container" style="max-width: 500px">
    <h1 class="text-center text-danger m-5">Delete Task</h1>
    <p class="text-center mb-5">Are you sure you want to delete this task?</p>
    <form action="" method="post">
      {% csrf_token %}
      <div class="row">
        <div class="col-6 text-center">
          <input class="btn btn-outline-danger" type="submit" value="Yes delete">
        </div>
        <div class="col-6 text-center">
          <a class="btn btn-outline-success" href="{% url 'manager:task-detail' pk=task.pk %}" >No</a>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

templates/manager/task_detail.html
{% extends "base.html" %}

{% block title %}
  Task: {{ task.name }}
{% endblock %}

{% block content %}
  
  {% include "includes/header.html" %}
  
  <div class="container" style="max-width: 900px">
    <h1 class="text-center mb-5">
      Task: {{ task.name }}
    </h1>
    {% if task.is_completed == False %}
      <div class="mb-5">
        <p>Click after completing the task.</p>
        <form action="{% url 'manager:task-completed' pk=task.pk %}" method="post">
          {% csrf_token %}
          <input type="submit" value="Completed" class="btn btn-outline-primary">
        </form>
      </div>
    {% endif %}
    <p><span class="font-weight-bold text-dark">Description:</span> {{ task.description }}</p>
    <p><span class="font-weight-bold text-dark">Deadline:</span> {{ task.deadline }}</p>
    <p>
      <span class="font-weight-bold text-dark">Is completed:</span>
      {% if task.is_completed == True %}
        <span class="text-success">{{ task.is_completed }}</span>
      {% else %}
        <span class="text-danger">{{ task.is_completed }}</span>
      {% endif %}
    </p>
    <p><span class="font-weight-bold text-dark">Task type:</span> {{ task.task_type.name }}</p>
    <p><span class="font-weight-bold text-dark">Priority:</span> {{ task.priority }}</p>
    <p class="mb-5"><span class="font-weight-bold text-dark">Assignees: </span>
      {% for worker in task.assignees.all %}
        <a href="{% url 'manager:worker-detail' pk=worker.pk %}">
          {{ worker.first_name }} {{ worker.last_name }}
        </a>
      {% endfor %}
    </p>
    <div>
      <a href="{% url 'manager:task-update' pk=task.pk %}" class="btn btn-dark">Update</a>
      <a href="{% url 'manager:task-delete' pk=task.pk %}" class="btn btn-outline-danger">Delete</a>
    </div>
  </div>
  
{% endblock %}

templates/manager/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}{{ object|yesno:"Update,Create" }} Task{% endblock %}

{% block content %}
  
  <div class="page-header section-height-100">
    <div class="oblique position-absolute top-0 h-100 d-md-block d-none max-width">
      <div class="oblique-image bg-cover position-absolute fixed-top ms-auto h-100 z-index-0 ms-n6" style="background-image:url(/static/img/IT/it_01.jpg)"></div>
    </div>
    <div class="container m-auto">
      <div class="row">
        <div class="col-lg-6 col-md-7 d-flex justify-content-center flex-column">
          <h1 class="text-gradient text-danger">{{ object|yesno:"Update,Create" }} Task</h1>
          <p class="lead pe-5 me-5">{{ object|yesno:"Update,Create" }} your Task. </p>
          <form method="post" action="">
            <div class="max-width">
              {% csrf_token %}
              {{ form|crispy }}
            </div>
            <div class="buttons">
              <input type="submit" class="btn bg-gradient-dark mt-4" value="{{ object|yesno:'Update,Create' }}">
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  
{% endblock %}

templates/manager/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Task list{% endblock %}

{% block content %}
  
  {% include "includes/header.html" %}
  
  <div class="container">  
    <div class="position-relative  shadow-lg mb-7">
      <div class="container border-bottom">
        <div class="row py-3">
          <div class="col-lg-4 text-start">
            <p class="lead text-dark pt-1 mb-0"></p>
          </div>
          <div class="col-lg-4 mt-1 text-center">
            <h1 class="text-dark">Task list</h1>
          </div>
          <div class="col-lg-4 text-end my-auto">
            <a href="{% url 'manager:task-create' %}" class="text-primary icon-move-right">Create new Task
              <i class="fas fa-arrow-right text-sm ms-1" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </div>
      <div class="ml-5 h-100">
        <form action="" method="get" class="form-row">
          {{ search_form|crispy }}
          <input type="submit" value="Search" class="btn btn-outline-dark">
        </form>
      </div>
      <div>
        {% if task_list %}
          <table class="table">
            <thead class="table-dark">
              <tr>
                <th>Task name</th>
                <th>Deadline</th>
                <th>Is completed</th>
                <th>Task type</th>
                <th>Assignees</th>
                <th>Priority</th>
              </tr>
            </thead>
            {% for task in task_list %}
              <tbody>
                <tr>
                  <td>
                    <a href="{% url 'manager:task-detail' pk=task.pk %}">
                      {{ task.name }}
                    </a>
                  </td>
                  <td>{{ task.deadline }}</td>
                  <td>
                    {% if task.is_completed == True %}
                      <span class="text-success">{{ task.is_completed }}</span>
                    {% else %}
                      <span class="text-danger">{{ task.is_completed }}</span>
                    {% endif %}
                  </td>
                  <td>{{ task.task_type }}</td>
                  <td>
                    {% for worker in task.assignees.all %}
                      <a href="{% url 'manager:worker-detail' pk=worker.pk %}">
                        {{ worker.first_name }} {{ worker.last_name }}{% if not forloop.last %}, 
                        {% endif %}
                      </a>
                    {% endfor %}
                  </td>
                  <td>{{ task.priority|capfirst }}</td>
                </tr>
              </tbody>
            {% endfor %}
          </table>
        {% endif %}
      </div>
    </div>
  </div>
  
{% endblock %}

templates/manager/task_type_list.html
{% extends "base.html" %}

{% block title %}Task type list{% endblock %}

{% block content %}
  
  {% include "includes/header.html" %}
  
  <div class="container">  
    <div class="position-relative border-radius-xl overflow-hidden shadow-lg mb-7">
      <div class="container border-bottom">
        <div class="row py-3">
          <div class="col-lg-4 text-start">
            <p class="lead text-dark pt-1 mb-0"></p>
          </div>
          <div class="col-lg-4 mt-1 text-center">
            <h1 class="text-dark">Task type list</h1>
          </div>
          <div class="col-lg-4 text-end my-auto">
            <a href="{% url 'manager:task-type-create' %}" class="text-primary icon-move-right">Create new Task type
              <i class="fas fa-arrow-right text-sm ms-1" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </div>
      <div>
        {% if tasktype_list %}
          <ul class="list-group-flush">
            {% for tasktype in tasktype_list %}
              <li class="list-group-item">{{ tasktype.name }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>
    </div>
  </div>
  
{% endblock %}

templates/manager/worker_confirm_delete.html
{% extends "base.html" %}

{% block title %}Worker confirm delete{% endblock %}

{% block content %}
  <div class="container" style="max-width: 500px">
    <h1 class="text-center text-danger m-5">Delete Worker</h1>
    <p class="text-center mb-5">Are you sure you want to delete this Worker?</p>
    <form action="" method="post">
      {% csrf_token %}
      <div class="row">
        <div class="col-6 text-center">
          <input class="btn btn-outline-danger" type="submit" value="Yes delete">
        </div>
        <div class="col-6 text-center">
          <a class="btn btn-outline-success" href="{% url 'manager:worker-detail' pk=worker.pk %}" >No</a>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

templates/manager/worker_detail.html
{% extends "base.html" %}

{% block title %}
  Worker: {{ worker.username }}, {{ worker.position.name }}
{% endblock %}

{% block content %}
  
  {% include "includes/header.html" %}
  
  <div class="container" style="max-width: 900px">
    <h1 class="text-center mb-5">
      {{ worker.first_name }} {{ worker.last_name }}
    </h1>
    <p><span class="font-weight-bold text-dark">Username:</span> {{ worker.username }}</p>
    <p><span class="font-weight-bold text-dark">Position:</span> {{ worker.position.name }}</p>
    {% if actual_tasks %}
      <h4 class="text-center mb-3">Actual Task</h4>
      <table class="table">
        <thead class="table-dark">
          <tr>
            <th>Task name</th>
            <th>Deadline</th>
          </tr>
        </thead>
        {% for task in actual_tasks %}
          <tbody>
            <tr>
              <td><a href="{% url 'manager:task-detail' pk=task.pk %}">{{ task.name }}</a></td>
              <td>{{ task.deadline }}</td>
            </tr>
          </tbody>
        {% endfor %}
      </table>
    {% endif %}
  
    {% if completed_tasks %}
      <h4 class="text-center mt-5">Completed Task</h4>
      <table class="table">
        <thead class="table-dark">
          <tr>
            <th>Task name</th>
          </tr>
        </thead>
        {% for task in completed_tasks %}
          <tbody>
            <tr>
              <td><a href="{% url 'manager:task-detail' pk=task.pk %}">{{ task.name }}</a></td>
            </tr>
          </tbody>
        {% endfor %}
      </table>
    {% endif %}
    <div class="mt-5 row">
      {% if user.is_staff == True %}
        <div class="col-3">
          <a href="{% url 'manager:worker-update' pk=worker.pk %}" class="btn btn-outline-dark">
            Update worker
          </a>
        </div>
        <div class="col-3">
          <a href="{% url 'manager:worker-delete' pk=worker.pk %}" class="btn btn-outline-danger">
            Delete worker
          </a>
        </div>
      {% else %}
        <div class="col-3">
          <a href="{% url 'manager:worker-update' pk=worker.pk %}" class="btn btn-outline-dark disabled">
            Update worker
          </a>
        </div>
        <div class="col-3">
          <a href="{% url 'manager:worker-delete' pk=worker.pk %}" class="btn btn-outline-danger disabled">
            Delete worker
          </a>
        </div>
        <p>Only the administrator can change information about employees. If necessary, contact the administrator.</p>
      {% endif %}
    </div>
  </div>
  
{% endblock %}

templates/manager/worker_list.html
{% extends "base.html" %}

{% block title %}Worker list{% endblock %}

{% block content %}
  
  {% include "includes/header.html" %}
  
  <div class="container">  
    <div class="position-relative  shadow-lg mb-7">
      <div class="container border-bottom">
        <div class="row py-3">
          <div class="col-lg-4 text-start">
            <p class="lead text-dark pt-1 mb-0"></p>
          </div>
          <div class="col-lg-4 mt-1 text-center">
            <h1 class="text-dark">Worker list</h1>
          </div>
          <div class="col-lg-4 text-end my-auto">
            <a href="{% url 'manager:worker-create' %}" class="text-primary icon-move-right">Create new Worker
              <i class="fas fa-arrow-right text-sm ms-1" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </div>
      <div>
        {% if worker_list %}
          <table class="table">
            <thead class="table-dark">
              <tr>
                <th>Username</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Position</th>
              </tr>
            </thead>
            {% for worker in worker_list %}
              <tbody>
                <tr>
                  <td>
                    <a href="{% url 'manager:worker-detail' pk=worker.pk %}">
                      {{ worker.username|capfirst }}
                    </a>
                  </td>
                  <td>{{ worker.first_name }}</td>
                  <td>{{ worker.last_name }}</td>
                  <td>{{ worker.position }}</td>
                </tr>
              </tbody>
            {% endfor %}
          </table>
        {% endif %}
      </div>
    </div>
  </div>
  
{% endblock %}