manager/urls.py
from django.urls import path

from manager import views

app_name = "manager"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "task-types/",
        views.TaskTypeListView.as_view(),
        name="task-type-list"
    ),
    path(
        "task-types/create/",
        views.TaskTypeCreateView.as_view(),
        name="task-type-create"
    ),
    path(
        "positions/",
        views.PositionListView.as_view(),
        name="position-list"
    ),
    path(
        "positions/create/",
        views.PositionCreateView.as_view(),
        name="position-create"
    ),
    path(
        "workers/",
        views.WorkerListView.as_view(),
        name="worker-list"
    ),
    path(
        "workers/<int:pk>/",
        views.WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path(
        "workers/create/",
        views.WorkerCreateView.as_view(),
        name="worker-create"
    ),
    path(
        "workers/<int:pk>/update/",
        views.WorkerUpdateView.as_view(),
        name="worker-update"
    ),
    path(
        "workers/<int:pk>/delete/",
        views.WorkerDeleteView.as_view(),
        name="worker-delete"
    ),
    path(
        "tasks/",
        views.TaskView.as_view(),
        name="task-list"
    ),
    path(
        "tasks/<int:pk>/",
        views.TaskDetailView.as_view(),
        name="task-detail"
    ),
    path(
        "tasks/create/",
        views.TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "tasks/<int:pk>/update/",
        views.TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        views.TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/completed-task/",
        views.TaskCompletedView.as_view(),
        name="task-completed"
    ),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("manager.urls", namespace="manager")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

templates/includes/footer.html
<footer class="footer pt-5 mt-5">
  <hr class="horizontal dark mb-5">
  <div class="container">
    <div class=" row">
      <div class="col-12">
        <div class="text-center">
          <p class="text-sm">
            &copy; Task Manager System by <a href="https://github.com/TIgor22">TIgor22</a>.
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/includes/header.html
{% load static %}
<header class="header-2">
  <div class="page-header section-height-75 relative" style="background-image: url({% static 'img/annie-spratt.jpg' %})">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 text-center mx-auto">
          <h1 class="text-white pt-3 mt-n5">
            Task Manager
          </h1>
          <p class="lead text-white mt-3">
            for the solution will cause within the company
          </p>
        </div>
      </div>
    </div>
    <div class="position-absolute w-100 z-index-1 bottom-0">
      <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
        <defs>
          <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"></path>
        </defs>
        <g class="moving-waves">
          <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40"></use>
          <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)"></use>
          <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)"></use>
          <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)"></use>
          <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)"></use>
          <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95"></use>
        </g>
      </svg>
    </div>
  </div>
</header>

templates/includes/navigation-dark.html
{% load static %}
<!-- Navbar Dark -->
<nav class="navbar navbar-expand-lg navbar-dark bg-gradient-dark z-index-3 py-3">
  <div class="container">
    <a class="navbar-brand text-white font-weight-bolder ms-sm-3" href="/" rel="tooltip" data-placement="bottom">
      Task Manager
    </a>
    <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon mt-2">
        <span class="navbar-toggler-bar bar1"></span>
        <span class="navbar-toggler-bar bar2"></span>
        <span class="navbar-toggler-bar bar3"></span>
      </span>
    </button>
    <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
      <ul class="navbar-nav navbar-nav-hover mx-auto">
        <li class="nav-item dropdown dropdown-hover mx-2">
          <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center" href="{% url 'manager:task-type-list' %}" aria-expanded="false">
            Task Types
          </a>
        </li>

        <li class="nav-item dropdown dropdown-hover mx-2">
          <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center" href="{% url 'manager:position-list' %}" aria-expanded="false">
            Positions
          </a>
        </li>

        <li class="nav-item dropdown dropdown-hover mx-2">
          <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center" href="{% url 'manager:worker-list' %}" aria-expanded="false">
            Workers
          </a>
        </li>
        <li class="nav-item dropdown dropdown-hover mx-2">
          <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center" href="{% url 'manager:task-list' %}" aria-expanded="false">
            Tasks
          </a>
        </li>
      </ul>
      <ul class="navbar-nav navbar-nav-hover">
        {% if request.user.is_authenticated %}
          <li class="nav-item dropdown dropdown-hover mx-2">
            <span class="nav-link justify-content-between">
              Hello {{ request.user.first_name|default:request.user.username|capfirst }}
            </span>
          </li>
          <li class="nav-item dropdown dropdown-hover mx-2">
            <a class="nav-link nav-link-icon me-2" href="{% url 'logout' %}">
              <i class="fa fa-sign-out me-1"></i>
              <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom">Logout</p>
            </a>
          </li>
        {% else %}
          <li class="nav-item dropdown dropdown-hover mx-2">
            <a class="nav-link justify-content-between" href="{% url 'login' %}">
              Log-in
            </a>
          </li>
        {% endif %}
        <li class="nav-item my-auto ms-3 ms-lg-0 ml-5">
          <a href="https://github.com/TIgor22/task-manager/" 
            target="_blank" 
            class="btn btn-sm  bg-gradient-primary btn-round mb-0 me-1 mt-2 mt-md-0">Project on github</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <section class="py-1">
    <div class="container">
      <div class="row justify-content-between py-2">
        <div class="col-lg-4 mx-auto">
          <ul class="pagination pagination-dark m-4 justify-content-center">
            {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}">
                  <span aria-hidden="true"><i class="fa fa-angle-double-left" aria-hidden="true"></i></span>
                </a>
              </li>
            {% else %}
              <li class="page-item disabled">               
                <span class="page-link">
                  <span aria-hidden="true"><i class="fa fa-angle-double-left" aria-hidden="true"></i></span>
                </span>
              </li>
            {% endif %}
            <li class="page-item active">
              <span class="page-link">{{ page_obj.number }}</span>
            </li>
            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}">
                  <span aria-hidden="true"><i class="fa fa-angle-double-right" aria-hidden="true"></i></span>
                </a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <span class="page-link">
                  <span aria-hidden="true"><i class="fa fa-angle-double-right" aria-hidden="true"></i></span>
                </span>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </section>
{% endif %}

templates/includes/scripts.html
{% load static %}

<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
  <script src="{% static 'js/plugins/prism.min.js' %}"></script>
  <script src="{% static 'js/plugins/parallax.min.js' %}"></script>